TITLE Mod file for component: Component(id=BackgroundL23RS_TO_CG3D_L23PyrRS_PoiSyn0 type=poissonFiringSynapse)

COMMENT

    This NEURON file has been generated by org.neuroml.export (see https://github.com/NeuroML/org.neuroml.export)
         org.neuroml.export  v1.5.2
         org.neuroml.model   v1.5.2
         jLEMS               v0.9.8.9

ENDCOMMENT

NEURON {
    POINT_PROCESS BackgroundL23RS_TO_CG3D_L23PyrRS_PoiSyn0
    ELECTRODE_CURRENT i
    RANGE averageRate                       : parameter
    RANGE averageIsi                        : parameter
    
    RANGE i                                 : exposure
    RANGE Syn_AMPA_SupPyr_SupPyr_tau        : parameter
    RANGE Syn_AMPA_SupPyr_SupPyr_gbase      : parameter
    RANGE Syn_AMPA_SupPyr_SupPyr_erev       : parameter
    
    RANGE Syn_AMPA_SupPyr_SupPyr_i          : exposure
    : Based on netstim.mod
    THREADSAFE : only true if every instance has its own distinct Random
    POINTER donotuse
}

UNITS {
    
    (nA) = (nanoamp)
    (uA) = (microamp)
    (mA) = (milliamp)
    (A) = (amp)
    (mV) = (millivolt)
    (mS) = (millisiemens)
    (uS) = (microsiemens)
    (molar) = (1/liter)
    (kHz) = (kilohertz)
    (mM) = (millimolar)
    (um) = (micrometer)
    (umol) = (micromole)
    (S) = (siemens)
    
}

PARAMETER {
    
    averageRate = 0.1 (kHz)
    averageIsi = 10 (ms)
    Syn_AMPA_SupPyr_SupPyr_tau = 2 (ms)
    Syn_AMPA_SupPyr_SupPyr_gbase = 1.8393972E-4 (uS)
    Syn_AMPA_SupPyr_SupPyr_erev = 0 (mV)
}

ASSIGNED {
    v (mV)
    
    Syn_AMPA_SupPyr_SupPyr_i (nA)          : derived variable
    
    i (nA)                                 : derived variable
    rate_tsince (ms/ms)
    rate_Syn_AMPA_SupPyr_SupPyr_g (uS/ms)
    rate_Syn_AMPA_SupPyr_SupPyr_A (uS/ms)
    donotuse
}

STATE {
    tsince (ms) 
    isi (ms) 
    Syn_AMPA_SupPyr_SupPyr_g (uS) 
    Syn_AMPA_SupPyr_SupPyr_A (uS) 
    
}

INITIAL {
    rates()
    rates() ? To ensure correct initialisation.
    
    tsince = 0
    
    isi = -  averageIsi  * log(1 - random_float(1))
    
    net_send(0, 1) : go to NET_RECEIVE block, flag 1, for initial state
    
    Syn_AMPA_SupPyr_SupPyr_g = 0
    
    Syn_AMPA_SupPyr_SupPyr_A = 0
    
}

BREAKPOINT {
    
    SOLVE states METHOD cnexp
    
    
}

NET_RECEIVE(flag) {
    
    LOCAL weight
    
    
    if (flag == 1) { : Setting watch for top level OnCondition...
        WATCH (tsince  >  isi) 1000
    }
    if (flag == 1000) {
    
        tsince = 0
    
        isi = -  averageIsi  * log(1 - random_float(1))
    
        : Child: Component(id=Syn_AMPA_SupPyr_SupPyr type=alphaSynapse)
    
        : This child is a synapse; defining weight
        weight = 1
    
        : paramMappings are: {BackgroundL23RS_TO_CG3D_L23PyrRS_PoiSyn0={tsince=tsince, isi=isi, averageRate=averageRate, averageIsi=averageIsi, i=i}, Syn_AMPA_SupPyr_SupPyr={g=Syn_AMPA_SupPyr_SupPyr_g, A=Syn_AMPA_SupPyr_SupPyr_A, tau=Syn_AMPA_SupPyr_SupPyr_tau, gbase=Syn_AMPA_SupPyr_SupPyr_gbase, erev=Syn_AMPA_SupPyr_SupPyr_erev, i=Syn_AMPA_SupPyr_SupPyr_i}, Syn_AMPA...
        : state_discontinuity(Syn_AMPA_SupPyr_SupPyr_A, Syn_AMPA_SupPyr_SupPyr_A  + ( Syn_AMPA_SupPyr_SupPyr_gbase *weight))
        Syn_AMPA_SupPyr_SupPyr_A = Syn_AMPA_SupPyr_SupPyr_A  + ( Syn_AMPA_SupPyr_SupPyr_gbase *weight)
    
        net_event(t)
        WATCH (tsince  >  isi) 1000
    
    }
    
}

DERIVATIVE states {
    rates()
    tsince' = rate_tsince 
    Syn_AMPA_SupPyr_SupPyr_g' = rate_Syn_AMPA_SupPyr_SupPyr_g 
    Syn_AMPA_SupPyr_SupPyr_A' = rate_Syn_AMPA_SupPyr_SupPyr_A 
    
}

PROCEDURE rates() {
    
    Syn_AMPA_SupPyr_SupPyr_i = Syn_AMPA_SupPyr_SupPyr_g  * ( Syn_AMPA_SupPyr_SupPyr_erev  - v) ? evaluable
    ? DerivedVariable is based on path: synapse/i, on: Component(id=BackgroundL23RS_TO_CG3D_L23PyrRS_PoiSyn0 type=poissonFiringSynapse), from synapse; Component(id=Syn_AMPA_SupPyr_SupPyr type=alphaSynapse)
    i = Syn_AMPA_SupPyr_SupPyr_i ? path based, prefix = 
    
    rate_tsince = 1 ? Note units of all quantities used here need to be consistent!
    
     
    rate_Syn_AMPA_SupPyr_SupPyr_g = (2.7182818284590451 *  Syn_AMPA_SupPyr_SupPyr_A  -  Syn_AMPA_SupPyr_SupPyr_g )/ Syn_AMPA_SupPyr_SupPyr_tau ? Note units of all quantities used here need to be consistent!
    rate_Syn_AMPA_SupPyr_SupPyr_A = - Syn_AMPA_SupPyr_SupPyr_A  /  Syn_AMPA_SupPyr_SupPyr_tau ? Note units of all quantities used here need to be consistent!
    
     
    
}


: Returns a float between 0 and max; implementation of random() as used in LEMS
FUNCTION random_float(max) {
    
    : This is not ideal, getting an exponential dist random number and then turning back to uniform
    : However this is the easiest what to ensure mod files with random methods fit into NEURON's
    : internal framework for managing internal number generation.
    random_float = exp(-1*erand())*max
    
}

:****************************************************
: Methods copied from netstim.mod in NEURON source

 
PROCEDURE seed(x) {
	set_seed(x)
}

VERBATIM
double nrn_random_pick(void* r);
void* nrn_random_arg(int argpos);
ENDVERBATIM


FUNCTION erand() {
VERBATIM
	if (_p_donotuse) {
		/*
		:Supports separate independent but reproducible streams for
		: each instance. However, the corresponding hoc Random
		: distribution MUST be set to Random.negexp(1)
		*/
		_lerand = nrn_random_pick(_p_donotuse);
	}else{
		/* only can be used in main thread */
		if (_nt != nrn_threads) {
           hoc_execerror("multithread random in NetStim"," only via hoc Random");
		}
ENDVERBATIM
		: the old standby. Cannot use if reproducible parallel sim
		: independent of nhost or which host this instance is on
		: is desired, since each instance on this cpu draws from
		: the same stream
		erand = exprand(1)
VERBATIM
	}
ENDVERBATIM
}

PROCEDURE noiseFromRandom() {
VERBATIM
 {
	void** pv = (void**)(&_p_donotuse);
	if (ifarg(1)) {
		*pv = nrn_random_arg(1);
	}else{
		*pv = (void*)0;
	}
 }
ENDVERBATIM
}

: End of methods copied from netstim.mod in NEURON source
:****************************************************

