TITLE Mod file for component: Component(id=Syn_NMDA_RSPyr_SupLTS type=blockingPlasticSynapse)

COMMENT

    This NEURON file has been generated by org.neuroml.export (see https://github.com/NeuroML/org.neuroml.export)
         org.neuroml.export  v1.5.2
         org.neuroml.model   v1.5.2
         jLEMS               v0.9.8.9

ENDCOMMENT

NEURON {
    POINT_PROCESS Syn_NMDA_RSPyr_SupLTS
    RANGE tauRise                           : parameter
    RANGE tauDecay                          : parameter
    RANGE peakTime                          : parameter
    RANGE waveformFactor                    : parameter
    RANGE gbase                             : parameter
    RANGE erev                              : parameter
    
    RANGE g                                 : exposure
    
    RANGE i                                 : exposure
    
    
    NONSPECIFIC_CURRENT i 
    RANGE blockMechanism_blockConcentration : parameter
    RANGE blockMechanism_scalingConc        : parameter
    RANGE blockMechanism_scalingVolt        : parameter
    
    RANGE blockMechanism_blockFactor        : exposure
    RANGE plasticityFactor                  : derived variable
    RANGE blockFactor                       : derived variable
    
}

UNITS {
    
    (nA) = (nanoamp)
    (uA) = (microamp)
    (mA) = (milliamp)
    (A) = (amp)
    (mV) = (millivolt)
    (mS) = (millisiemens)
    (uS) = (microsiemens)
    (molar) = (1/liter)
    (kHz) = (kilohertz)
    (mM) = (millimolar)
    (um) = (micrometer)
    (umol) = (micromole)
    (S) = (siemens)
    
}

PARAMETER {
    
    tauRise = 1 (ms)
    tauDecay = 100 (ms)
    peakTime = 4.651687 (ms)
    waveformFactor = 1.0581977 
    gbase = 1.5E-4 (uS)
    erev = 0 (mV)
    blockMechanism_blockConcentration = 1.5 (mM)
    blockMechanism_scalingConc = 3.5700006 (mM)
    blockMechanism_scalingVolt = 16.129032 (mV)
}

ASSIGNED {
    ? Standard Assigned variables with baseSynapse
    v (mV)
    celsius (degC)
    temperature (K)
    
    blockMechanism_blockFactor             : derived variable
    
    plasticityFactor                       : derived variable
    
    blockFactor                            : derived variable
    
    g (uS)                                 : derived variable
    
    i (nA)                                 : derived variable
    rate_A (/ms)
    rate_B (/ms)
    
}

STATE {
    A  
    B  
    
}

INITIAL {
    temperature = celsius + 273.15
    
    rates()
    rates() ? To ensure correct initialisation.
    
    A = 0
    
    B = 0
    
}

BREAKPOINT {
    
    SOLVE states METHOD cnexp
    
    
}

NET_RECEIVE(weight) {
    
    : paramMappings . : {Syn_NMDA_RSPyr_SupLTS={A=A, B=B, tauRise=tauRise, tauDecay=tauDecay, peakTime=peakTime, waveformFactor=waveformFactor, gbase=gbase, erev=erev, g=g, i=i, plasticityFactor=plasticityFactor, blockFactor=blockFactor}, Syn_NMDA_RSPyr_SupLTS_notes={}, Syn_NMDA_RSPyr_SupLTS_blockMechanism={blockConcentration=blockMechanism_blockConcentration, s...
    : state_discontinuity(A, A  + (weight *  plasticityFactor  *   waveformFactor  )) : From Syn_NMDA_RSPyr_SupLTS
    A = A  + (weight *  plasticityFactor  *   waveformFactor  ) : From Syn_NMDA_RSPyr_SupLTS
    
    : paramMappings . : {Syn_NMDA_RSPyr_SupLTS={A=A, B=B, tauRise=tauRise, tauDecay=tauDecay, peakTime=peakTime, waveformFactor=waveformFactor, gbase=gbase, erev=erev, g=g, i=i, plasticityFactor=plasticityFactor, blockFactor=blockFactor}, Syn_NMDA_RSPyr_SupLTS_notes={}, Syn_NMDA_RSPyr_SupLTS_blockMechanism={blockConcentration=blockMechanism_blockConcentration, s...
    : state_discontinuity(B, B  + (weight *  plasticityFactor  *   waveformFactor  )) : From Syn_NMDA_RSPyr_SupLTS
    B = B  + (weight *  plasticityFactor  *   waveformFactor  ) : From Syn_NMDA_RSPyr_SupLTS
    
}

DERIVATIVE states {
    rates()
    A' = rate_A 
    B' = rate_B 
    
}

PROCEDURE rates() {
    
    blockMechanism_blockFactor = 1/(1 + ( blockMechanism_blockConcentration  /  blockMechanism_scalingConc )* exp(-1 * (v /  blockMechanism_scalingVolt ))) ? evaluable
    ? DerivedVariable is based on path: plasticityMechanisms[*]/plasticityFactor, on: Component(id=Syn_NMDA_RSPyr_SupLTS type=blockingPlasticSynapse), from plasticityMechanisms; null
    ? Path not present in component, using factor: 1
    
    plasticityFactor = 1 
    
    ? DerivedVariable is based on path: blockMechanisms[*]/blockFactor, on: Component(id=Syn_NMDA_RSPyr_SupLTS type=blockingPlasticSynapse), from blockMechanisms; Component(id=null type=voltageConcDepBlockMechanism)
    ? multiply applied to all instances of blockFactor in: <blockMechanisms> ([Component(id=null type=voltageConcDepBlockMechanism)]))
    blockFactor = blockMechanism_blockFactor ? path based, prefix = 
    
    g = blockFactor  *  gbase  * (  B   -   A  ) ? evaluable
    i = -1 * g  * (  erev   - v) ? evaluable
    rate_A = -  A   /  tauRise ? Note units of all quantities used here need to be consistent!
    rate_B = -  B   /  tauDecay ? Note units of all quantities used here need to be consistent!
    
     
    
     
    
}

